<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }

    /**
     * {@inheritDoc}
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

        return parent::__isset($name);

    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'name', 'email', 'password', 'rememberToken', 'created_at', 'updated_at', '' . "\0" . 'Entity\\User' . "\0" . 'lists', 'connection', 'table', 'primaryKey', 'keyType', 'perPage', 'incrementing', 'timestamps', 'attributes', 'original', 'relations', 'hidden', 'visible', 'appends', 'fillable', 'guarded', 'dates', 'dateFormat', 'casts', 'touches', 'observables', 'with', 'morphClass', 'exists', 'wasRecentlyCreated'];
        }

        return ['__isInitialized__', 'id', 'name', 'email', 'password', 'rememberToken', 'created_at', 'updated_at', '' . "\0" . 'Entity\\User' . "\0" . 'lists', 'connection', 'table', 'primaryKey', 'keyType', 'perPage', 'incrementing', 'timestamps', 'attributes', 'original', 'relations', 'hidden', 'visible', 'appends', 'fillable', 'guarded', 'dates', 'dateFormat', 'casts', 'touches', 'observables', 'with', 'morphClass', 'exists', 'wasRecentlyCreated'];
    }

    /**
     * {@inheritDoc}
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
        parent::__wakeup();
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getGlobalScopes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGlobalScopes', []);

        return parent::getGlobalScopes();
    }

    /**
     * {@inheritDoc}
     */
    public function fill(array $attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fill', [$attributes]);

        return parent::fill($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function forceFill(array $attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'forceFill', [$attributes]);

        return parent::forceFill($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function newInstance($attributes = array (
), $exists = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newInstance', [$attributes, $exists]);

        return parent::newInstance($attributes, $exists);
    }

    /**
     * {@inheritDoc}
     */
    public function newFromBuilder($attributes = array (
), $connection = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newFromBuilder', [$attributes, $connection]);

        return parent::newFromBuilder($attributes, $connection);
    }

    /**
     * {@inheritDoc}
     */
    public function fresh($with = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fresh', [$with]);

        return parent::fresh($with);
    }

    /**
     * {@inheritDoc}
     */
    public function load($relations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'load', [$relations]);

        return parent::load($relations);
    }

    /**
     * {@inheritDoc}
     */
    public function append($attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'append', [$attributes]);

        return parent::append($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function hasOne($related, $foreignKey = NULL, $localKey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasOne', [$related, $foreignKey, $localKey]);

        return parent::hasOne($related, $foreignKey, $localKey);
    }

    /**
     * {@inheritDoc}
     */
    public function morphOne($related, $name, $type = NULL, $id = NULL, $localKey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'morphOne', [$related, $name, $type, $id, $localKey]);

        return parent::morphOne($related, $name, $type, $id, $localKey);
    }

    /**
     * {@inheritDoc}
     */
    public function belongsTo($related, $foreignKey = NULL, $otherKey = NULL, $relation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'belongsTo', [$related, $foreignKey, $otherKey, $relation]);

        return parent::belongsTo($related, $foreignKey, $otherKey, $relation);
    }

    /**
     * {@inheritDoc}
     */
    public function morphTo($name = NULL, $type = NULL, $id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'morphTo', [$name, $type, $id]);

        return parent::morphTo($name, $type, $id);
    }

    /**
     * {@inheritDoc}
     */
    public function getActualClassNameForMorph($class)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActualClassNameForMorph', [$class]);

        return parent::getActualClassNameForMorph($class);
    }

    /**
     * {@inheritDoc}
     */
    public function hasMany($related, $foreignKey = NULL, $localKey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasMany', [$related, $foreignKey, $localKey]);

        return parent::hasMany($related, $foreignKey, $localKey);
    }

    /**
     * {@inheritDoc}
     */
    public function hasManyThrough($related, $through, $firstKey = NULL, $secondKey = NULL, $localKey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasManyThrough', [$related, $through, $firstKey, $secondKey, $localKey]);

        return parent::hasManyThrough($related, $through, $firstKey, $secondKey, $localKey);
    }

    /**
     * {@inheritDoc}
     */
    public function morphMany($related, $name, $type = NULL, $id = NULL, $localKey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'morphMany', [$related, $name, $type, $id, $localKey]);

        return parent::morphMany($related, $name, $type, $id, $localKey);
    }

    /**
     * {@inheritDoc}
     */
    public function belongsToMany($related, $table = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'belongsToMany', [$related, $table, $foreignKey, $otherKey, $relation]);

        return parent::belongsToMany($related, $table, $foreignKey, $otherKey, $relation);
    }

    /**
     * {@inheritDoc}
     */
    public function morphToMany($related, $name, $table = NULL, $foreignKey = NULL, $otherKey = NULL, $inverse = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'morphToMany', [$related, $name, $table, $foreignKey, $otherKey, $inverse]);

        return parent::morphToMany($related, $name, $table, $foreignKey, $otherKey, $inverse);
    }

    /**
     * {@inheritDoc}
     */
    public function morphedByMany($related, $name, $table = NULL, $foreignKey = NULL, $otherKey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'morphedByMany', [$related, $name, $table, $foreignKey, $otherKey]);

        return parent::morphedByMany($related, $name, $table, $foreignKey, $otherKey);
    }

    /**
     * {@inheritDoc}
     */
    public function joiningTable($related)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'joiningTable', [$related]);

        return parent::joiningTable($related);
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', []);

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function forceDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'forceDelete', []);

        return parent::forceDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservableEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservableEvents', []);

        return parent::getObservableEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservableEvents(array $observables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservableEvents', [$observables]);

        return parent::setObservableEvents($observables);
    }

    /**
     * {@inheritDoc}
     */
    public function addObservableEvents($observables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObservableEvents', [$observables]);

        return parent::addObservableEvents($observables);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObservableEvents($observables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObservableEvents', [$observables]);

        return parent::removeObservableEvents($observables);
    }

    /**
     * {@inheritDoc}
     */
    public function update(array $attributes = array (
), array $options = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', [$attributes, $options]);

        return parent::update($attributes, $options);
    }

    /**
     * {@inheritDoc}
     */
    public function push()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'push', []);

        return parent::push();
    }

    /**
     * {@inheritDoc}
     */
    public function save(array $options = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', [$options]);

        return parent::save($options);
    }

    /**
     * {@inheritDoc}
     */
    public function saveOrFail(array $options = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveOrFail', [$options]);

        return parent::saveOrFail($options);
    }

    /**
     * {@inheritDoc}
     */
    public function touchOwners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'touchOwners', []);

        return parent::touchOwners();
    }

    /**
     * {@inheritDoc}
     */
    public function touches($relation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'touches', [$relation]);

        return parent::touches($relation);
    }

    /**
     * {@inheritDoc}
     */
    public function touch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'touch', []);

        return parent::touch();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$value]);

        return parent::setCreatedAt($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$value]);

        return parent::setUpdatedAt($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAtColumn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAtColumn', []);

        return parent::getCreatedAtColumn();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAtColumn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAtColumn', []);

        return parent::getUpdatedAtColumn();
    }

    /**
     * {@inheritDoc}
     */
    public function freshTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'freshTimestamp', []);

        return parent::freshTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function freshTimestampString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'freshTimestampString', []);

        return parent::freshTimestampString();
    }

    /**
     * {@inheritDoc}
     */
    public function newQuery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newQuery', []);

        return parent::newQuery();
    }

    /**
     * {@inheritDoc}
     */
    public function newQueryWithoutScope($scope)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newQueryWithoutScope', [$scope]);

        return parent::newQueryWithoutScope($scope);
    }

    /**
     * {@inheritDoc}
     */
    public function newQueryWithoutScopes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newQueryWithoutScopes', []);

        return parent::newQueryWithoutScopes();
    }

    /**
     * {@inheritDoc}
     */
    public function newEloquentBuilder($query)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newEloquentBuilder', [$query]);

        return parent::newEloquentBuilder($query);
    }

    /**
     * {@inheritDoc}
     */
    public function newCollection(array $models = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newCollection', [$models]);

        return parent::newCollection($models);
    }

    /**
     * {@inheritDoc}
     */
    public function newPivot(\Illuminate\Database\Eloquent\Model $parent, array $attributes, $table, $exists)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'newPivot', [$parent, $attributes, $table, $exists]);

        return parent::newPivot($parent, $attributes, $table, $exists);
    }

    /**
     * {@inheritDoc}
     */
    public function getTable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTable', []);

        return parent::getTable();
    }

    /**
     * {@inheritDoc}
     */
    public function setTable($table)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTable', [$table]);

        return parent::setTable($table);
    }

    /**
     * {@inheritDoc}
     */
    public function getKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKey', []);

        return parent::getKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getQueueableId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQueueableId', []);

        return parent::getQueueableId();
    }

    /**
     * {@inheritDoc}
     */
    public function getKeyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeyName', []);

        return parent::getKeyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeyName($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeyName', [$key]);

        return parent::setKeyName($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualifiedKeyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualifiedKeyName', []);

        return parent::getQualifiedKeyName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRouteKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRouteKey', []);

        return parent::getRouteKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getRouteKeyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRouteKeyName', []);

        return parent::getRouteKeyName();
    }

    /**
     * {@inheritDoc}
     */
    public function usesTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'usesTimestamps', []);

        return parent::usesTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function getMorphClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMorphClass', []);

        return parent::getMorphClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getPerPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerPage', []);

        return parent::getPerPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerPage($perPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerPage', [$perPage]);

        return parent::setPerPage($perPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getForeignKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForeignKey', []);

        return parent::getForeignKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getHidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHidden', []);

        return parent::getHidden();
    }

    /**
     * {@inheritDoc}
     */
    public function setHidden(array $hidden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHidden', [$hidden]);

        return parent::setHidden($hidden);
    }

    /**
     * {@inheritDoc}
     */
    public function addHidden($attributes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHidden', [$attributes]);

        return parent::addHidden($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function makeVisible($attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'makeVisible', [$attributes]);

        return parent::makeVisible($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function makeHidden($attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'makeHidden', [$attributes]);

        return parent::makeHidden($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function withHidden($attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'withHidden', [$attributes]);

        return parent::withHidden($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible(array $visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function addVisible($attributes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVisible', [$attributes]);

        return parent::addVisible($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function setAppends(array $appends)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppends', [$appends]);

        return parent::setAppends($appends);
    }

    /**
     * {@inheritDoc}
     */
    public function getFillable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFillable', []);

        return parent::getFillable();
    }

    /**
     * {@inheritDoc}
     */
    public function fillable(array $fillable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fillable', [$fillable]);

        return parent::fillable($fillable);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuarded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuarded', []);

        return parent::getGuarded();
    }

    /**
     * {@inheritDoc}
     */
    public function guard(array $guarded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'guard', [$guarded]);

        return parent::guard($guarded);
    }

    /**
     * {@inheritDoc}
     */
    public function isFillable($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFillable', [$key]);

        return parent::isFillable($key);
    }

    /**
     * {@inheritDoc}
     */
    public function isGuarded($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isGuarded', [$key]);

        return parent::isGuarded($key);
    }

    /**
     * {@inheritDoc}
     */
    public function totallyGuarded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totallyGuarded', []);

        return parent::totallyGuarded();
    }

    /**
     * {@inheritDoc}
     */
    public function getTouchedRelations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTouchedRelations', []);

        return parent::getTouchedRelations();
    }

    /**
     * {@inheritDoc}
     */
    public function setTouchedRelations(array $touches)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTouchedRelations', [$touches]);

        return parent::setTouchedRelations($touches);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncrementing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncrementing', []);

        return parent::getIncrementing();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncrementing($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncrementing', [$value]);

        return parent::setIncrementing($value);
    }

    /**
     * {@inheritDoc}
     */
    public function toJson($options = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', [$options]);

        return parent::toJson($options);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function attributesToArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'attributesToArray', []);

        return parent::attributesToArray();
    }

    /**
     * {@inheritDoc}
     */
    public function relationsToArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'relationsToArray', []);

        return parent::relationsToArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', [$key]);

        return parent::getAttribute($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValue($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValue', [$key]);

        return parent::getAttributeValue($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelationValue($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelationValue', [$key]);

        return parent::getRelationValue($key);
    }

    /**
     * {@inheritDoc}
     */
    public function hasGetMutator($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGetMutator', [$key]);

        return parent::hasGetMutator($key);
    }

    /**
     * {@inheritDoc}
     */
    public function hasCast($key, $types = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasCast', [$key, $types]);

        return parent::hasCast($key, $types);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasts', []);

        return parent::getCasts();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($key, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', [$key, $value]);

        return parent::setAttribute($key, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function hasSetMutator($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasSetMutator', [$key]);

        return parent::hasSetMutator($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getDates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDates', []);

        return parent::getDates();
    }

    /**
     * {@inheritDoc}
     */
    public function fromDateTime($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromDateTime', [$value]);

        return parent::fromDateTime($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFormat($format)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFormat', [$format]);

        return parent::setDateFormat($format);
    }

    /**
     * {@inheritDoc}
     */
    public function fromJson($value, $asObject = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromJson', [$value, $asObject]);

        return parent::fromJson($value, $asObject);
    }

    /**
     * {@inheritDoc}
     */
    public function replicate(array $except = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'replicate', [$except]);

        return parent::replicate($except);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributes', []);

        return parent::getAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function setRawAttributes(array $attributes, $sync = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRawAttributes', [$attributes, $sync]);

        return parent::setRawAttributes($attributes, $sync);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginal($key = NULL, $default = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginal', [$key, $default]);

        return parent::getOriginal($key, $default);
    }

    /**
     * {@inheritDoc}
     */
    public function syncOriginal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'syncOriginal', []);

        return parent::syncOriginal();
    }

    /**
     * {@inheritDoc}
     */
    public function syncOriginalAttribute($attribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'syncOriginalAttribute', [$attribute]);

        return parent::syncOriginalAttribute($attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function isDirty($attributes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDirty', [$attributes]);

        return parent::isDirty($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirty', []);

        return parent::getDirty();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelations', []);

        return parent::getRelations();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelation($relation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelation', [$relation]);

        return parent::getRelation($relation);
    }

    /**
     * {@inheritDoc}
     */
    public function relationLoaded($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'relationLoaded', [$key]);

        return parent::relationLoaded($key);
    }

    /**
     * {@inheritDoc}
     */
    public function setRelation($relation, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelation', [$relation, $value]);

        return parent::setRelation($relation, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function setRelations(array $relations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelations', [$relations]);

        return parent::setRelations($relations);
    }

    /**
     * {@inheritDoc}
     */
    public function getConnection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnection', []);

        return parent::getConnection();
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectionName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectionName', []);

        return parent::getConnectionName();
    }

    /**
     * {@inheritDoc}
     */
    public function setConnection($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConnection', [$name]);

        return parent::setConnection($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getMutatedAttributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMutatedAttributes', []);

        return parent::getMutatedAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', [$offset]);

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', [$offset]);

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', [$offset, $value]);

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', [$offset]);

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function __unset($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__unset', [$key]);

        return parent::__unset($key);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, $parameters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$method, $parameters]);

        return parent::__call($method, $parameters);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifierName', []);

        return parent::getAuthIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifier', []);

        return parent::getAuthIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthPassword', []);

        return parent::getAuthPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberToken', []);

        return parent::getRememberToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRememberToken($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRememberToken', [$value]);

        return parent::setRememberToken($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberTokenName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberTokenName', []);

        return parent::getRememberTokenName();
    }

    /**
     * {@inheritDoc}
     */
    public function can($ability, $arguments = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'can', [$ability, $arguments]);

        return parent::can($ability, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailForPasswordReset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailForPasswordReset', []);

        return parent::getEmailForPasswordReset();
    }

    /**
     * {@inheritDoc}
     */
    public function cant($ability, $arguments = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cant', [$ability, $arguments]);

        return parent::cant($ability, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function cannot($ability, $arguments = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cannot', [$ability, $arguments]);

        return parent::cannot($ability, $arguments);
    }

}
